### ISSUE TITLE
[REQUEST] Support interface to C++ integral libraries

### ISSUE THREAD

**Issue by wilhadams** [theochem/gbasis#112]
**Is your feature request related to a problem? Please describe.**
For standard integrals, it would be beneficial to support fast C++ libraries, which will likely remain faster than `gbasis` regardless of any optimizations we make.

**Additional context**

There are many possible libraries: libint2, libcint, libmint, libreta, ...

[Psi4Numpy uses `libmints` to access the `libint` library](https://github.com/psi4/psi4numpy/blob/master/Tutorials/01_Psi4NumPy-Basics/1e_mints-helper.ipynb)

**Comment by wilhadams** [comment]
[PySCF uses `libcint` as their AO integral engine](https://sunqm.github.io/pyscf/tutorial.html#access-ao-integrals)

**Comment by PaulWAyers** [comment]
@msricher has a detailed list of things to think about for this (via e-mail), which she should add to the issue for discussion. 

The other thing I know to consider is [libreta](http://www.zhjun-sci.com/software-libreta-download.php).

Both [libint](https://github.com/evaleev/libint) and [libcint](https://github.com/sunqm/libcint) seem to be actively maintained on GitHub, which is a point in their favor. 

I'll let @msricher put her comments here, and then we can make a decision on the best interface.

**Comment by PaulWAyers** [comment]
Not urgent, but the most useful "additional feature" we could have would be an interface to the derivative integrals we need for geometry optimization. We haven't supported that in the past, but we could do it easily with automatic differentiation too.

**Comment by PaulWAyers** [comment]
We considered `libint2`, `libcint`, `libmint`, and `libreta` and decided to support libint. (Hat tip to @msricher for guiding this decision-making process.) The basic rationale for `libcint` was that it was stand-alone (unlike `libmint`) and that its shared object (`.so` file) can be directly loaded into Python; it was also the package that @msricher was most familiar with. We don't intend to support other libraries, but would welcome contributions from others along those lines.

This was closed with pull request #137
