### ISSUE TITLE
[REQUEST] Spherically-averaged atomic densities and derivatives

### ISSUE THREAD

**Issue by PaulWAyers** [theochem/gbasis#124]
**Is your feature request related to a problem? Please describe.**
The goal is to be able to evaluate the spherically-averaged density, its derivatives, and the kinetic-energy density for an atom.

**Is there a specific integral/formula that you would like implemented?**
There are several possible ways to do this, including using fractional occupation numbers or (probably easier) neglecting the spherical harmonic contribution when evaluating the density and its derivatives.

**Is there a change to the code or algorithm you would like to see?**
This might be a different set of routines for spherically averaging or maybe it is a flag for existing routines.

**Comment by PaulWAyers** [comment]
I think there is a solution in `AtomDB` for this. We should add a utility (probably in the HORTON 3 repository, not the `gbasis` code) to fix this.

**Comment by gabrielasd** [comment]
Yes, in AtomDB the atomic densities are averaged in the scripts that compile datasets that use basis sets. We don't have a utility function for this, so indeed it would be good to have.

The procedure there depends on Grid. It uses the method `spherical_average` from an AtomGrid instance which generates a spline of the atomic density.
To evaluate the initial atomic density that is passed to `spherical_average` we use `eval_dens` function from GBasis and an atomic grid from the AtomGrid instance.

In case it helps here are the relevant lines in one of AtomDB compilation script:
Generate an atomic grid:
https://github.com/theochem/AtomDB/blob/5369631832658ff880d24b04de63500deb0023d1/atomdb/datasets/gaussian/__init__.py#L151

Evaluate the density on the atomic grid:
https://github.com/theochem/AtomDB/blob/5369631832658ff880d24b04de63500deb0023d1/atomdb/datasets/gaussian/__init__.py#L158

Generate a spline function of spherically averaged density:
https://github.com/theochem/AtomDB/blob/5369631832658ff880d24b04de63500deb0023d1/atomdb/datasets/gaussian/__init__.py#L165

**Comment by PaulWAyers** [comment]
So the workflow is essentially entirely based on `grid` then, using the `spherical_average` functionality. `AtomDB` provides a useful example, and I remember that we had a long discussion explaining why we opted to do this numerically instead of analytically, but alas it must have been offline. 

https://github.com/theochem/grid/blob/37dfebce5d1ecf826ded3103c145b8a60afa8b79/src/grid/atomgrid.py#L530

I will close this issue then.
