### ISSUE TITLE
Update PyPI

### ISSUE THREAD

**Issue by VHchavez** [theochem/gbasis#125]
**Describe**
Hello folks, 
Thanks for developing gbasis! :)
I am using gbasis in a package I am writing. I want to make part of my CI, but the pypi installation has a version from 2017. Would it be possible to get it updated to the most recent commit? Unless there has not been any relevant changes in the meantime. 

Thanks a lot!

**Comment by FarnazH** [comment]
@VHchavez, thanks for your comments. We have made a new Pypi release in recent updates to the package. Let us know if there are any issues.
