### ISSUE TITLE
[REQUEST] Gbasis Documentation website

### ISSUE THREAD

**Issue by leila-pujal** [theochem/gbasis#132]
Gbasis Documentation website

This issue is to request the creation of a Gbasis Documentation website similar to https://grid.qcdevs.org/. The most complete set of notes about Gbasis functionality and what is already implemented can be found within the repo [here](https://github.com/theochem/gbasis/blob/master/docs/notes.pdf). Example tutorials are being developed and updates kept track in issue #133

**Comment by RichRick1** [comment]
@leila-pujal I will need the logo at some point, so feel free to share ideas

**Comment by leila-pujal** [comment]
@RichRick1, sure I'll think about it.

**Comment by PaulWAyers** [comment]
The logo that we had in mind (I think it was @Ali-Tehrani ?) was just the word gbasis, but the i was a Gaussian, and the dot of the i was a contour map of a Gaussian. One could lean in further and make the "loops" of the g, b, and a contour maps of a Gaussian, but it's probably a bit cluttered. I would probably use a g where the "loop" is filled with the contour map of a Gaussian as the favicon, though.

**Comment by RichRick1** [comment]
@PaulWAyers here are few examples with more gaussiany g and g, that looks more like a contour map (my preference). Is that what you had in mind?
<img width="316" alt="Screenshot 2023-10-25 at 10 12 25 AM jpeg" src="https://github.com/theochem/gbasis/assets/36164007/3da9815e-b713-445b-a731-a130d93923e0">
![Screenshot 2023-10-25 at 10 13 22 AM](https://github.com/theochem/gbasis/assets/36164007/6e3c158a-8e8e-4d6e-9fe0-a36e080adef6)

**Comment by PaulWAyers** [comment]
That's sort of what I had in mind for the favicon. (I like the second better, btw.)

**Comment by Ali-Tehrani** [comment]
I do remember making a logo with the "i" as a Gaussian and the dot is contours of the Gaussian.  I'll check my old laptop tonight to see if I still have it.

**Comment by RichRick1** [comment]
@PaulWAyers you mean the asymmetric one? Also, do we have any domain name reserved for the package?

**Comment by PaulWAyers** [comment]
I mean the symmetric one (the bigger image).

**Comment by PaulWAyers** [comment]
It'll take a little while to propagate, but `gbasis.qcdevs.org` should work soon.

**Comment by PaulWAyers** [comment]
While the web site isn't perfect, it is up and running now.
