### ISSUE TITLE
[REQUEST]Gbasis functionality/features jupyter notebooks

### ISSUE THREAD

**Issue by leila-pujal** [theochem/gbasis#133]
This issue is to request a set of Jupyter notebooks to show the functionality/features of Gbasis package. This follows recent decisions to incorporate notebooks for qc-devs packages that are easy to use and modify so all the features can be accessed readily.

**Comment by maximilianvz** [comment]
Comment!

**Comment by FarnazH** [comment]
@leila-pujal and @marco-2023 are there any other notebook/example that needs to be added? If so, please list them here.

**Comment by leila-pujal** [comment]
This is issue is completed after merging PRs #172, #158, #147 and #146
