### ISSUE TITLE
Update `CONTRIBUTING.Md`

### ISSUE THREAD

**Issue by kimt33** [theochem/gbasis#14]
It should have a more welcoming tone. Code of conduct may be moved to a different location.

**Comment by tovrstra** [comment]
The code of conduct rubbed me off the wrong way, despite being a standard formulation. I wish we could write something with the same end goal but in a way that it also motivates the reader to follow good practices.

One downside of setting a list of morally charged expectations or rules is that they express a lack of trust in the best intentions of anyone interested in contributing. This lack of trust is most pronounced when the text goes into detail on abusive cases and enforcement. Anyone willing to help, is usually doing this with good intentions. If anything should be mentioned first, it would be to express your trust in the contributor's good intentions. Without it, the code of conduct goes against its own principles, i.e. not trusting someone who is willing to help.

A second downside of setting just a list of expectations is that they provide no insight. Some insight into why a code of conduct, despite best intentions, is needed, will motivate everyone to pay more attention to it. I would guess (but may be wrong) that unpleasant electronic communication is (at least initially) rarely on purpose, but rather the consequence of someone with good intentions writing in a poor state of mind. E.g. being too short on time, being too sleep-deprived, being too frustrated, and so on, easily results in communication that is not received well on the other end of the line.

Some practical hints to address the above problem could be helpful. Setting expectations is good, provided there is some context. Good advice can only help to make it happen. I'm not an expert but I'll try to give some unavoidably incomplete hints. 

1) Don't type while you're angry or upset. Take a break, go for a short walk and try again. If that doesn't work, try to get a third person to bring you back to your senses.

2) When you need to criticize, always frame it positively, even when you feel you're criticizing something that is completely and utterly wrong.

As I said, with a good state of mind, these two things are obvious, but they are useful as a reminder when there is not enough caffeine in the universe to keep you focussed.

**Comment by PaulWAyers** [comment]
We are formulating a standard contributing guidelines for all [QC-Devs](https://qcdevs.org/) packages. However, we already have a [standard code of conduct](https://github.com/theochem/QCDevs_www/blob/web/_guidelines/QCDevsCodeOfConduct.md) (an updated and extended version of this one). I'll update that code-of-conduct and add a pointer to it.
