### ISSUE TITLE
[BUG] Python 3.9, Python 3.10 nan result on test_compute_differential_operator_integrals_multiarray 

### ISSUE THREAD

**Issue by Ali-Tehrani** [theochem/gbasis#154]
**Describe the bug**

While I'm trying to set up github actions to use pytest. I've came across an error on ubuntu systems for only python 3.9, python 3.10, python=3.11 and for windows system, python=3.9,3.10,3.11. It passes on my own system and python=3.7

The test is `test_compute_differential_operator_integrals_multiarray` in [test_diff_operator_int](https://github.com/theochem/gbasis/blob/f0ad9db12d7b4adc3b0d4fd3dbc31356ee0f9a3b/tests/test_diff_operator_int.py#L234C5-L234C60).
 
 It seems that they both return `nans`.  Note this requires to fix the test as done in #151 
Python=3.7, I'll get the following value: order, angmom_a, angmom_b:
` [3 0 0] [2 1 0] [2 0 0] -0.0007958223786576885`
Python-3.10, I'm getting this array to be all infinity and nans

The error comes from teh normalization factor calculated in https://github.com/theochem/gbasis/blob/f0ad9db12d7b4adc3b0d4fd3dbc31356ee0f9a3b/tests/test_diff_operator_int.py#L283

which comes from the factorial2

**To Reproduce**

```bash
conda create -n py310 python=3.10
conda activate py310
pip install .
pytest -v .
```

**Expected behaviour**

**Screenshots**

See the run: https://github.com/theochem/gbasis/actions/runs/7491475696/job/20392775547?pr=151
```python
         for i, single_order in enumerate(orders_diff):
            for j, angmom_a in enumerate(angmoms_a):
                for k, angmom_b in enumerate(angmoms_b):
>                   assert np.allclose(
                        _compute_differential_operator_integrals(
                            np.array([single_order]),
                            coord_a,
                            np.array([angmom_a]),
                            exps_a,
                            coeffs_a,
                            norm_a,
                            coord_b,
                            np.array([angmom_b]),
                            exps_b,
                            coeffs_b,
                            norm_b,
                        )[0, 0, j, 0, k],
                        test[i, 0, j, 0, k]
                    )
E                   assert False
E                    +  where False = <function allclose at 0x7fe17171d4b0>(nan, nan)
E                    +    where <function allclose at 0x7fe17171d4b0> = np.allclose
```
**System Information:**
 - OS:
 - Python version:
 - NumPy version:
 - SciPy version:

**Additional context**

**Comment by Ali-Tehrani** [comment]
Fixed the bug, the factorial2 from gbasis.utils wasn't being used. So it is the same problem as before

**Comment by PaulWAyers** [comment]
I'll close the issue, as it seems OK. Good to remember as there seems to be some (not entirely relevant, it seems, though) recent progress on `scipy.special.factorial2`.
