### ISSUE TITLE
[BUG] Old website

### ISSUE THREAD

**Issue by RichRick1** [theochem/gbasis#155]
Apparently, there is an old website in the web: https://gbasis.readthedocs.io/en/latest/index.html
@PaulWAyers @FarnazH  can we somehow crush it?  
I think here is an instruction on how to do that https://groups.google.com/g/read-the-docs/c/xJyqg7QSX9Y

**Comment by PaulWAyers** [comment]
Good catch. This is *very* old. I've never used read-the-docs so I'm not sure.

**Comment by Charlie-1-3** [comment]
If the project has already been deleted then it might be a caching error.
Otherwise, Under [cog]Admin button, scroll to the bottom and next to Save is a Delete Project option. This will help delete the old project.

**Comment by PaulWAyers** [comment]
Does anyone know who made the read-the-docs site? Maybe it's @tczorro or @kimt33 ?

**Comment by PaulWAyers** [comment]
It seems we are stuck with this as no one knows who made the web site. I'm going to close the issue for now.
