### ISSUE TITLE
Covert note.pdf to scientific documentation

### ISSUE THREAD

**Issue by FarnazH** [theochem/gbasis#160]
Convert the `notes.pdf` to a scientific documentation on the website, excluding the code-snippet examples.

**Comment by Aditish51** [comment]
@FarnazH Can I work on this issue?

**Comment by FarnazH** [comment]
Thanks @Aditish51 for offering to help. After discussing with other members of QC-Devs we decided just to add a link to this PDF file on GBasis's website.
