### ISSUE TITLE
[BUG] Typos in documentation & parser.py

### ISSUE THREAD

**Issue by 3laaHisham** [theochem/gbasis#168]
**Describe the bug**

While navigating through the notes.pdf and later at parser.py, I think I found some unintended words in place.

**To Reproduce**

1. /docs/notes.pdf Section 6.2 Multipole moment intergral:
Instead of: "To compute the **overlap** of a set of molecular orbitals"
It should be: "To compute the **moment** of a set of molecular orbitals"
2. /gbasis/parser.py Line 217:
Instead of: "**Tolerance** must be provided as True or False."
It should be: "**Overlap** must be provided as True or False."

**Expected behaviour**

Minimal Effect on users and developers' experience.

**Screenshots**

1. 
![Docs](https://github.com/theochem/gbasis/assets/72917870/809c70c3-5695-469c-bb15-6ae5f364932a)
2. 
![parser](https://github.com/theochem/gbasis/assets/72917870/906cfa49-6380-4e6f-bcb2-1e992cb4dac5)

**System Information:**
 - OS:
 - Python version:
 - NumPy version:
 - SciPy version:

**Additional context**

**Comment by Charlie-1-3** [comment]
I have corrected the above-mentioned typos in the documentation.
Also if I find any more of these errors in the docs, I will see to it immediately.
