### ISSUE TITLE
[BUG] `from_iodata` not working after API change of `iodata`

### ISSUE THREAD

**Issue by FarnazH** [theochem/gbasis#195]
The API change introduced in https://github.com/theochem/iodata/pull/373 breaks the [`from_iodata`](https://github.com/theochem/gbasis/blob/3e063ad3a3ce40430ac1eafeffc6f92e79888ff1/gbasis/wrappers.py#L89) function. So, `gbasis` does not work with the latest source code of `iodata`.

**Comment by tovrstra** [comment]
Oops, sorry for that. I'll take care of it. This should be easy to fix...
