### ISSUE TITLE
Clarify references to contractions in gbasis/contractions.py

### ISSUE THREAD

**Issue by wilhadams** [theochem/gbasis#26]
The `num_contr` property states that it returns the number of contractions in the `ContractedCartesianGaussians` class, however, this seems ambiguously worded. While the data class contains the information for every contracted GTO of a given angular momentum (_l_ ), for a total of (_l_ + 1)*(_l_ + 2) / 2 CGTOs (which is the number given as `num_contr`), each CGTO is a contraction of a given number of Cartesian primitive GTOs, specified by the number of coefficients/exponents given. It seems like we should be careful to be consistent with our usage in the docstring.

**Comment by wilhadams** [comment]
This is also important for references to contractions/shells in `gbasis.deriv` functions `eval_shell`, `eval_deriv_shell`, which should be consistent with usage in `gbasis.lincomb` function `lincomb_blocks_evals`, which is addressed in pull request #30

**Comment by kimt33** [comment]
I think that the current version of the data class explicitly makes the distinction between the spherical and Cartesian contractions. I also believe that the usage of `shell` was removed for most of the code and is used carefully in the docstring and documentation.
