### ISSUE TITLE
Overlap on arbitrary number of centres and arbitrary number of  dimensions

### ISSUE THREAD

**Issue by FarnazH** [theochem/gbasis#4]
API:
`compute_overlap(center_1, shell_1,  convention_1, center_2, shell_2, convention_2)`
`compute_overlap_multicenter(shells, centers, convention)`

**Comment by PaulWAyers** [comment]
See my notes. This is intended as a binomial-theorem algorithm, which is "brute strength" in some sense.

Adding arbitrary-order multipoles to this is quite easy and should be considered....

**Comment by kimt33** [comment]
I'm not sure what a multicenter overlap is, but if it is multipole moment, we have these features.

**Comment by kimt33** [comment]
See https://github.com/theochem/gbasis/blob/master/gbasis/electron_repulsion.py

**Comment by kimt33** [comment]
If not, it'll be possible to make feature requests through the issue, so a new issue can be posted if we're missing the multicenter overlap.
