### ISSUE TITLE
1-Electron Integrals

### ISSUE THREAD

**Issue by FarnazH** [theochem/gbasis#5]
Arbitrary order multipoles and derivative (a special case is kinetic energy density)

**Comment by PaulWAyers** [comment]
I would do this with the Obara-Saika recursion. Helgaker has formulas for arbitrary-order multipoles and arbitrary-order derivatives explained.  A special case would be overlap integrals (zeroth-order multipoles and zeroth-order derivatives.) That may be faster than the binomial implementation, and provides a consistency unit test.

**Comment by kimt33** [comment]
Both available in the current version.
