### ISSUE TITLE
2-Electron Integrals

### ISSUE THREAD

**Issue by FarnazH** [theochem/gbasis#6]
Given 4 `shells` and `centers` compute integrals.

**Comment by PaulWAyers** [comment]
This would have a form like
`compute_2el(shell1,center1,shell2,center2,shell3,center3,shell4,center4,conventions)`
but could be a tuple of shells,centers,conventions too. 

This should wrap a lower-level function that supports unconventional (e.g., range-separated) 2-electron integrals, something like
`compute_2el_type(shells,centers,conventions,Boys_function)
where different types of Boys functions can be passed depending on the integral of interest.

Algorithm should be basically Obara-Saika. Not so important to have bleeding-edge performance here but should try not to be stupid.... OS1 (cf. Helgaker) or Hamilton-Schaefer or PRISM or Ishida or....

I'm OK with McMurchie-Davidson too, though.

**Comment by PaulWAyers** [comment]
Use mpmath for the Boys function. It means that we get arbitrary-precision integrals 'for free.' Performance is good at standard precision too, and the next Intel hardware may even support arbitrary precision natively.

http://mpmath.org/

**Comment by kimt33** [comment]
See https://github.com/theochem/gbasis/blob/master/gbasis/electron_repulsion.py
