### ISSUE TITLE
Nuclear-electron attraction energy

### ISSUE THREAD

**Issue by PaulWAyers** [theochem/gbasis#7]
`compute_external_potential(shell1, center1, shell2, center2, conventions, point_charges, point_coords)`

Compute the potential due to a product of 2 shells of Gaussians with an array of point charges and their centers. Gives the matrix of external potential integrals

* generalize to compute_external_potential_type() to compute this for different types of potentials (not necessarily point charges). The only change is that a different Boys function is used, so there should be a low-level function of the form
`compute_extpot(shell1, center1, shell2, center2, conventions, Boys_function)`
(or something like that).

Algorithm could be McMurchie-Davidson or Obara-Saika but probably Obara-Saika is a bit easier?

**Comment by PaulWAyers** [comment]
Use mpmath for the Boys function. It means that we get arbitrary-precision integrals 'for free.' Performance is good at standard precision too, and the next Intel hardware may even support arbitrary precision natively.

http://mpmath.org/
https://www.anandtech.com/show/13405/intel-10nm-cannon-lake-and-core-i3-8121u-deep-dive-review/4 (hat-tip Matt via Slack)

**Comment by kimt33** [comment]
See https://github.com/theochem/gbasis/blob/master/gbasis/nuclear_electron_attraction.py
